// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ProductAdvisor.Infrastructure;

#nullable disable

namespace ProductAdvisor.Infrastructure.Migrations
{
    [DbContext(typeof(AdvisorDbContext))]
    [Migration("20260811151723_AddStoreInfoKnowledgeBase")]
    partial class AddStoreInfoKnowledgeBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("advisor")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductAdvisor.Domain.ConversationSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("conversation_sessions", "advisor");
                });

            modelBuilder.Entity("ProductAdvisor.Domain.DocumentChunk", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChunkId");

                    b.HasIndex("DocumentId", "Order")
                        .IsUnique();

                    b.HasIndex("StoreId", "Status");

                    b.ToTable("document_chunks", "advisor");
                });

            modelBuilder.Entity("ProductAdvisor.Domain.StoreDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersedesDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.HasIndex("StoreId", "Status", "DocumentType");

                    b.ToTable("store_documents", "advisor");
                });

            modelBuilder.Entity("ProductAdvisor.Domain.ConversationSession", b =>
                {
                    b.OwnsOne("ProductAdvisor.Domain.ClarificationQuestion", "PendingClarification", b1 =>
                        {
                            b1.Property<Guid>("ConversationSessionSessionId");

                            b1.Property<string>("MissingField")
                                .IsRequired();

                            b1.Property<string>("QuestionText")
                                .IsRequired();

                            b1.HasKey("ConversationSessionSessionId");

                            b1.ToTable("conversation_sessions", "advisor");

                            b1
                                .ToJson("PendingClarification")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConversationSessionSessionId");
                        });

                    b.OwnsMany("ProductAdvisor.Domain.ConversationMessage", "Messages", b1 =>
                        {
                            b1.Property<Guid>("ConversationSessionSessionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Role")
                                .IsRequired();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("Timestamp");

                            b1.HasKey("ConversationSessionSessionId", "__synthesizedOrdinal");

                            b1.ToTable("conversation_sessions", "advisor");

                            b1
                                .ToJson("Messages")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConversationSessionSessionId");
                        });

                    b.OwnsMany("ProductAdvisor.Domain.SearchResultReference", "LastSearchResults", b1 =>
                        {
                            b1.Property<Guid>("ConversationSessionSessionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<Guid>("ProductId");

                            b1.HasKey("ConversationSessionSessionId", "__synthesizedOrdinal");

                            b1.ToTable("conversation_sessions", "advisor");

                            b1
                                .ToJson("LastSearchResults")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConversationSessionSessionId");
                        });

                    b.OwnsOne("ProductAdvisor.Domain.UserRequirement", "CurrentRequirement", b1 =>
                        {
                            b1.Property<Guid>("ConversationSessionSessionId");

                            b1.PrimitiveCollection<string>("AvailabilityRequirements")
                                .IsRequired();

                            b1.Property<string>("Category");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("Language")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Preferences")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("RequiredFeatures")
                                .IsRequired();

                            b1.Property<int?>("ResultLimit");

                            b1.Property<string>("Units");

                            b1.HasKey("ConversationSessionSessionId");

                            b1.ToTable("conversation_sessions", "advisor");

                            b1
                                .ToJson("CurrentRequirement")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConversationSessionSessionId");

                            b1.OwnsOne("ProductAdvisor.Domain.Money", "Budget", b2 =>
                                {
                                    b2.Property<Guid>("UserRequirementConversationSessionSessionId");

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();

                                    b2.HasKey("UserRequirementConversationSessionSessionId");

                                    b2.ToTable("conversation_sessions", "advisor");

                                    b2.WithOwner()
                                        .HasForeignKey("UserRequirementConversationSessionSessionId");
                                });

                            b1.Navigation("Budget");
                        });

                    b.Navigation("CurrentRequirement")
                        .IsRequired();

                    b.Navigation("LastSearchResults");

                    b.Navigation("Messages");

                    b.Navigation("PendingClarification");
                });

            modelBuilder.Entity("ProductAdvisor.Domain.DocumentChunk", b =>
                {
                    b.HasOne("ProductAdvisor.Domain.StoreDocument", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductAdvisor.Domain.StoreDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
