// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductAdvisor.Infrastructure;

#nullable disable

namespace ProductAdvisor.Infrastructure.Migrations
{
    [DbContext(typeof(AdvisorDbContext))]
    partial class AdvisorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("advisor")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductAdvisor.Domain.ConversationSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.ToTable("conversation_sessions", "advisor");
                });

            modelBuilder.Entity("ProductAdvisor.Domain.ConversationSession", b =>
                {
                    b.OwnsOne("ProductAdvisor.Domain.ClarificationQuestion", "PendingClarification", b1 =>
                        {
                            b1.Property<Guid>("ConversationSessionSessionId");

                            b1.Property<string>("MissingField")
                                .IsRequired();

                            b1.Property<string>("QuestionText")
                                .IsRequired();

                            b1.HasKey("ConversationSessionSessionId");

                            b1.ToTable("conversation_sessions", "advisor");

                            b1
                                .ToJson("PendingClarification")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConversationSessionSessionId");
                        });

                    b.OwnsMany("ProductAdvisor.Domain.ConversationMessage", "Messages", b1 =>
                        {
                            b1.Property<Guid>("ConversationSessionSessionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Role")
                                .IsRequired();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("Timestamp");

                            b1.HasKey("ConversationSessionSessionId", "__synthesizedOrdinal");

                            b1.ToTable("conversation_sessions", "advisor");

                            b1
                                .ToJson("Messages")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConversationSessionSessionId");
                        });

                    b.OwnsOne("ProductAdvisor.Domain.UserRequirement", "CurrentRequirement", b1 =>
                        {
                            b1.Property<Guid>("ConversationSessionSessionId");

                            b1.Property<string>("Category");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("Language")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Preferences")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("RequiredFeatures")
                                .IsRequired();

                            b1.HasKey("ConversationSessionSessionId");

                            b1.ToTable("conversation_sessions", "advisor");

                            b1
                                .ToJson("CurrentRequirement")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ConversationSessionSessionId");

                            b1.OwnsOne("ProductAdvisor.Domain.Money", "Budget", b2 =>
                                {
                                    b2.Property<Guid>("UserRequirementConversationSessionSessionId");

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();

                                    b2.HasKey("UserRequirementConversationSessionSessionId");

                                    b2.ToTable("conversation_sessions", "advisor");

                                    b2.WithOwner()
                                        .HasForeignKey("UserRequirementConversationSessionSessionId");
                                });

                            b1.Navigation("Budget");
                        });

                    b.Navigation("CurrentRequirement")
                        .IsRequired();

                    b.Navigation("Messages");

                    b.Navigation("PendingClarification");
                });
#pragma warning restore 612, 618
        }
    }
}
